# Импорт

In [21]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from imblearn.over_sampling import SMOTE

# Загружаем DataSet

In [22]:
models = pd.read_csv('../../../Data/DataLaba2/neo_task_moded_norm.csv')
models

,est_diameter_max,relative_velocity,miss_distance,absolute_magnitude,hazardous
0,-0.999187,-0.528599,-0.972789,0.407593,0.0
1,-0.998421,-0.935292,-0.126239,0.290780,0.0
2,-0.997101,-0.534989,0.748307,0.182311,0.0
3,-0.999016,-0.650926,-0.663033,0.374218,0.0
4,-0.992669,-0.430407,0.906601,0.015436,0.0
...,...,...,...,...,...
90831,-0.999105,-0.805214,-0.956459,0.390905,0.0
90832,-0.994184,-0.792225,-0.103853,0.057155,0.0
90833,-0.998183,-0.019492,0.462918,0.265749,0.0
90834,-0.997704,-0.615181,-0.279547,0.224030,0.0
90835,-0.995575,-0.330062,-0.029164,0.106383,0.0

In [23]:
X, y = models.drop('hazardous', axis=1), models['hazardous']

In [24]:
X_balanced, y_balanced = SMOTE().fit_resample(X, y)

In [25]:
X_balanced['hazardous'] = y_balanced

In [26]:
X_balanced

,est_diameter_max,relative_velocity,miss_distance,absolute_magnitude,hazardous
0,-0.999187,-0.528599,-0.972789,0.407593,0.0
1,-0.998421,-0.935292,-0.126239,0.290780,0.0
2,-0.997101,-0.534989,0.748307,0.182311,0.0
3,-0.999016,-0.650926,-0.663033,0.374218,0.0
4,-0.992669,-0.430407,0.906601,0.015436,0.0
...,...,...,...,...,...
163987,-0.994367,-0.604209,-0.841236,0.062991,1.0
163988,-0.993778,-0.757087,-0.160396,0.045115,1.0
163989,-0.989685,-0.114495,-0.067884,-0.046048,1.0
163990,-0.986634,-0.067341,0.716200,-0.093033,1.0
163991,-0.991556,-0.530904,-0.851264,-0.010082,1.0

In [27]:

X_balanced.to_csv('../../../Data/DataLaba2/neo_task_smoted.csv', index=False)